### ISSUE TITLE
MapView

### ISSUE THREAD

**Issue by bertbeck** [halkar/XamarinExtendedMap#1]
Is there a way to create this without have a dependency on Xamarin.Forms.Maps ?

I've been trying to do something like:

```
public class MapControlRenderer : ViewRenderer<MapControl, global::Android.Gms.Maps.MapView>, IOnMapReadyCallback
{}
```

But so far no luck. It would be good to have something we have complete control of and knowledge of how it works. I've done this for IOS - it worked well.

**Comment by halkar** [comment]
Probably there is but this was not a real project but some sample code to show how to expose tap event.
